services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:epap3r@db:5432/e-paper
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: e-paper
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: epap3r
      POSTGRES_DB: e-paper
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
