name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit

  validate-docker:
    name: Validate Docker Environment
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Installation
        run: |
          if ! [ -x "$(command -v docker)" ]; then
            echo "Docker não encontrado. Instalando Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
          else
            echo "Docker já está instalado."
          fi

      - name: Check Docker Compose Installation
        run: |
          if ! [ -x "$(command -v docker-compose)" ]; then
            echo "Docker Compose não encontrado. Instalando Docker Compose..."
            curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose já está instalado."
          fi

  deploy:
    name: Deploy to Production
    environment: e-paper
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure DockerHub Secrets are Present
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Error: DockerHub credentials are missing."
            exit 1
          fi

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/e-paper:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/e-paper:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/e-paper:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/e-paper:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/e-paper:latest

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/e-paper:latest
          cd /home/e-paper
          docker compose down
          docker compose up -d
          EOF
